Page({
  data: {
    name: '',
    category: '',
    difficulty: 0,
    content: [],
    loading: true,
    isAuthorized: false
  },

  onLoad(options) {
    const userInfo = wx.getStorageSync('userInfo')
    this.setData({
      isAuthorized: !!userInfo
    })
    
    const name = decodeURIComponent(options.name || '')
    wx.setNavigationBarTitle({ title: name })
    this.setData({ name })
    
    if (userInfo) {
      this.loadRecipe(name)
    }
  },

  loadRecipe(name) {
    this.setData({ loading: true })
    wx.cloud.callFunction({
      name: 'foodApi',
      data: { action: 'getRecipeDetail', name: name },
      success: (res) => {
        if (res.result && res.result.data) {
          const recipe = res.result.data
          const parsedContent = this.parseContent(recipe.content)
          this.setData({
            category: recipe.category || '',
            difficulty: recipe.difficulty || 0,
            content: parsedContent,
            loading: false
          })
        } else {
          this.setData({
            content: [{ type: 'p', text: '暂未找到该菜谱的详细做法' }],
            loading: false
          })
        }
      },
      fail: (err) => {
        console.error('加载菜谱失败:', err)
        this.setData({
          content: [{ type: 'p', text: '加载失败，请稍后重试' }],
          loading: false
        })
      }
    })
  },

  getAllRecipes() {
    return [
      { name: '拔丝土豆', difficulty: 2, category: '素菜' },
      { name: '白灼菜心', difficulty: 1, category: '素菜' },
      { name: '包菜炒鸡蛋粉丝', difficulty: 2, category: '素菜' },
      { name: '菠菜炒鸡蛋', difficulty: 1, category: '素菜' },
      { name: '炒滑蛋', difficulty: 2, category: '素菜' },
      { name: '炒茄子', difficulty: 2, category: '素菜' },
      { name: '炒青菜', difficulty: 1, category: '素菜' },
      { name: '葱煎豆腐', difficulty: 2, category: '素菜' },
      { name: '脆皮豆腐', difficulty: 3, category: '素菜' },
      { name: '地三鲜', difficulty: 3, category: '素菜' },
      { name: '干锅花菜', difficulty: 3, category: '素菜' },
      { name: '蚝油三鲜菇', difficulty: 2, category: '素菜' },
      { name: '蚝油生菜', difficulty: 1, category: '素菜' },
      { name: '红烧冬瓜', difficulty: 2, category: '素菜' },
      { name: '红烧茄子', difficulty: 2, category: '素菜' },
      { name: '虎皮青椒', difficulty: 2, category: '素菜' },
      { name: '话梅煮毛豆', difficulty: 2, category: '素菜' },
      { name: '鸡蛋羹', difficulty: 2, category: '素菜' },
      { name: '微波炉鸡蛋羹', difficulty: 1, category: '素菜' },
      { name: '蒸箱鸡蛋羹', difficulty: 2, category: '素菜' },
      { name: '鸡蛋花', difficulty: 1, category: '素菜' },
      { name: '鸡蛋火腿炒黄瓜', difficulty: 2, category: '素菜' },
      { name: '茄子炖土豆', difficulty: 2, category: '素菜' },
      { name: '家常日本豆腐', difficulty: 2, category: '素菜' },
      { name: '椒盐玉米', difficulty: 2, category: '素菜' },
      { name: '金钱蛋', difficulty: 3, category: '素菜' },
      { name: '金针菇日本豆腐煲', difficulty: 3, category: '素菜' },
      { name: '烤茄子', difficulty: 2, category: '素菜' },
      { name: '榄菜肉末四季豆', difficulty: 3, category: '素菜' },
      { name: '雷椒皮蛋', difficulty: 2, category: '素菜' },
      { name: '凉拌豆腐', difficulty: 1, category: '素菜' },
      { name: '凉拌黄瓜', difficulty: 1, category: '素菜' },
      { name: '凉拌金针菇', difficulty: 1, category: '素菜' },
      { name: '凉拌木耳', difficulty: 1, category: '素菜' },
      { name: '凉拌莴笋', difficulty: 1, category: '素菜' },
      { name: '凉拌油麦菜', difficulty: 1, category: '素菜' },
      { name: '皮蛋豆腐', difficulty: 1, category: '素菜' },
      { name: '蒲烧茄子', difficulty: 3, category: '素菜' },
      { name: '芹菜拌茶树菇', difficulty: 2, category: '素菜' },
      { name: '清炒花菜', difficulty: 1, category: '素菜' },
      { name: '清蒸南瓜', difficulty: 1, category: '素菜' },
      { name: '陕北熬豆角', difficulty: 3, category: '素菜' },
      { name: '上汤娃娃菜', difficulty: 2, category: '素菜' },
      { name: '手撕包菜', difficulty: 1, category: '素菜' },
      { name: '水油焖蔬菜', difficulty: 2, category: '素菜' },
      { name: '松仁玉米', difficulty: 2, category: '素菜' },
      { name: '素炒豆角', difficulty: 2, category: '素菜' },
      { name: '酸辣土豆丝', difficulty: 2, category: '素菜' },
      { name: '蒜蓉空心菜', difficulty: 1, category: '素菜' },
      { name: '蒜蓉西兰花', difficulty: 1, category: '素菜' },
      { name: '糖拌西红柿', difficulty: 1, category: '素菜' },
      { name: '莴笋叶煎饼', difficulty: 2, category: '素菜' },
      { name: '西红柿炒鸡蛋', difficulty: 1, category: '素菜' },
      { name: '西红柿豆腐汤羹', difficulty: 2, category: '素菜' },
      { name: '西葫芦炒鸡蛋', difficulty: 1, category: '素菜' },
      { name: '小炒藕丁', difficulty: 2, category: '素菜' },
      { name: '洋葱炒鸡蛋', difficulty: 1, category: '素菜' },
      { name: '印度葫芦丸子', difficulty: 4, category: '素菜' },
      { name: '印度土豆花菜', difficulty: 3, category: '素菜' },
      { name: '油醋爆蛋', difficulty: 2, category: '素菜' },
      { name: '澳门湿版免治牛肉饭', difficulty: 4, category: '荤菜' },
      { name: '巴基斯坦牛肉咖喱', difficulty: 4, category: '荤菜' },
      { name: '白菜猪肉炖粉条', difficulty: 3, category: '荤菜' },
      { name: '豉汁排骨', difficulty: 3, category: '荤菜' },
      { name: '豉汁蒸白鱔', difficulty: 4, category: '荤菜' },
      { name: '带把肘子', difficulty: 5, category: '荤菜' },
      { name: '冬瓜酿肉', difficulty: 3, category: '荤菜' },
      { name: '豆豉鲮鱼油麦菜', difficulty: 2, category: '荤菜' },
      { name: '番茄红酱', difficulty: 3, category: '荤菜' },
      { name: '粉蒸肉', difficulty: 3, category: '荤菜' },
      { name: '腐乳肉', difficulty: 3, category: '荤菜' },
      { name: '干煸仔鸡', difficulty: 4, category: '荤菜' },
      { name: '宫保鸡丁', difficulty: 3, category: '荤菜' },
      { name: '咕噜肉', difficulty: 4, category: '荤菜' },
      { name: '广式萝卜牛腩', difficulty: 4, category: '荤菜' },
      { name: '贵州辣子鸡', difficulty: 4, category: '荤菜' },
      { name: '荷兰豆炒腊肠', difficulty: 2, category: '荤菜' },
      { name: '黑椒牛柳', difficulty: 3, category: '荤菜' },
      { name: '红烧鸡翅', difficulty: 2, category: '荤菜' },
      { name: '简易红烧肉', difficulty: 3, category: '荤菜' },
      { name: '南派红烧肉', difficulty: 4, category: '荤菜' },
      { name: '红烧猪蹄', difficulty: 4, category: '荤菜' },
      { name: '湖南家常红烧肉', difficulty: 3, category: '荤菜' },
      { name: '虎皮肘子', difficulty: 5, category: '荤菜' },
      { name: '黄瓜炒肉', difficulty: 1, category: '荤菜' },
      { name: '黄焖鸡', difficulty: 3, category: '荤菜' },
      { name: '黄油鸡', difficulty: 3, category: '荤菜' },
      { name: '徽派红烧肉', difficulty: 4, category: '荤菜' },
      { name: '回锅肉', difficulty: 3, category: '荤菜' },
      { name: '尖椒炒牛肉', difficulty: 3, category: '荤菜' },
      { name: '尖叫牛蛙', difficulty: 4, category: '荤菜' },
      { name: '煎烤羊排', difficulty: 3, category: '荤菜' },
      { name: '姜炒鸡', difficulty: 2, category: '荤菜' },
      { name: '姜葱捞鸡', difficulty: 3, category: '荤菜' },
      { name: '酱牛肉', difficulty: 4, category: '荤菜' },
      { name: '酱排骨', difficulty: 4, category: '荤菜' },
      { name: '茭白炒肉', difficulty: 2, category: '荤菜' },
      { name: '椒盐排条', difficulty: 3, category: '荤菜' },
      { name: '芥末罗氏虾', difficulty: 3, category: '荤菜' },
      { name: '咖喱肥牛', difficulty: 2, category: '荤菜' },
      { name: '烤鸡翅', difficulty: 2, category: '荤菜' },
      { name: '可乐鸡翅', difficulty: 2, category: '荤菜' },
      { name: '口水鸡', difficulty: 4, category: '荤菜' },
      { name: '辣椒炒肉', difficulty: 2, category: '荤菜' },
      { name: '老妈蹄花', difficulty: 4, category: '荤菜' },
      { name: '老式锅包肉', difficulty: 4, category: '荤菜' },
      { name: '冷吃兔', difficulty: 4, category: '荤菜' },
      { name: '荔枝肉', difficulty: 4, category: '荤菜' },
      { name: '凉拌鸡丝', difficulty: 2, category: '荤菜' },
      { name: '卤菜', difficulty: 4, category: '荤菜' },
      { name: '萝卜炖羊排', difficulty: 4, category: '荤菜' },
      { name: '麻辣香锅', difficulty: 4, category: '荤菜' },
      { name: '麻婆豆腐', difficulty: 3, category: '荤菜' },
      { name: '蚂蚁上树', difficulty: 3, category: '荤菜' },
      { name: '梅菜扣肉', difficulty: 4, category: '荤菜' },
      { name: '奶酪培根通心粉', difficulty: 3, category: '荤菜' },
      { name: '牛排', difficulty: 3, category: '荤菜' },
      { name: '农家一碗香', difficulty: 3, category: '荤菜' },
      { name: '啤酒鸭', difficulty: 3, category: '荤菜' },
      { name: '黔式腊肠娃娃菜', difficulty: 3, category: '荤菜' },
      { name: '青椒土豆炒肉', difficulty: 2, category: '荤菜' },
      { name: '清蒸鳜鱼', difficulty: 3, category: '荤菜' },
      { name: '肉饼炖蛋', difficulty: 2, category: '荤菜' },
      { name: '杀猪菜', difficulty: 4, category: '荤菜' },
      { name: '山西过油肉', difficulty: 4, category: '荤菜' },
      { name: '商芝肉', difficulty: 4, category: '荤菜' },
      { name: '瘦肉土豆片', difficulty: 2, category: '荤菜' },
      { name: '水煮牛肉', difficulty: 4, category: '荤菜' },
      { name: '水煮肉片', difficulty: 4, category: '荤菜' },
      { name: '蒜苔炒肉末', difficulty: 2, category: '荤菜' },
      { name: '台式卤肉饭', difficulty: 3, category: '荤菜' },
      { name: '糖醋里脊', difficulty: 3, category: '荤菜' },
      { name: '糖醋排骨', difficulty: 3, category: '荤菜' },
      { name: '甜辣烤全翅', difficulty: 3, category: '荤菜' },
      { name: '土豆炖排骨', difficulty: 3, category: '荤菜' },
      { name: '无骨鸡爪', difficulty: 3, category: '荤菜' },
      { name: '西红柿牛腩', difficulty: 4, category: '荤菜' },
      { name: '西红柿土豆炖牛肉', difficulty: 4, category: '荤菜' },
      { name: '乡村啤酒鸭', difficulty: 3, category: '荤菜' },
      { name: '香干芹菜炒肉', difficulty: 2, category: '荤菜' },
      { name: '香干肉丝', difficulty: 2, category: '荤菜' },
      { name: '香菇滑鸡', difficulty: 3, category: '荤菜' },
      { name: '香煎五花肉', difficulty: 2, category: '荤菜' },
      { name: '香辣鸡爪煲', difficulty: 4, category: '荤菜' },
      { name: '湘祁米夫鸭', difficulty: 4, category: '荤菜' },
      { name: '小炒黄牛肉', difficulty: 4, category: '荤菜' },
      { name: '小炒鸡肝', difficulty: 3, category: '荤菜' },
      { name: '小炒肉', difficulty: 2, category: '荤菜' },
      { name: '小米辣炒肉', difficulty: 2, category: '荤菜' },
      { name: '小酥肉', difficulty: 3, category: '荤菜' },
      { name: '新疆大盘鸡', difficulty: 4, category: '荤菜' },
      { name: '血浆鸭', difficulty: 5, category: '荤菜' },
      { name: '羊排焖面', difficulty: 4, category: '荤菜' },
      { name: '洋葱炒猪肉', difficulty: 2, category: '荤菜' },
      { name: '意式烤鸡', difficulty: 3, category: '荤菜' },
      { name: '鱼香茄子', difficulty: 3, category: '荤菜' },
      { name: '鱼香肉丝', difficulty: 3, category: '荤菜' },
      { name: '枝竹羊腩煲', difficulty: 4, category: '荤菜' },
      { name: '猪皮冻', difficulty: 4, category: '荤菜' },
      { name: '猪肉烩酸菜', difficulty: 3, category: '荤菜' },
      { name: '柱候牛腩', difficulty: 4, category: '荤菜' },
      { name: '孜然牛肉', difficulty: 3, category: '荤菜' },
      { name: '醉排骨', difficulty: 4, category: '荤菜' },
      { name: '白灼虾', difficulty: 1, category: '水产' },
      { name: '鳊鱼炖豆腐', difficulty: 3, category: '水产' },
      { name: '蛏抱蛋', difficulty: 3, category: '水产' },
      { name: '葱烧海参', difficulty: 5, category: '水产' },
      { name: '葱油桂鱼', difficulty: 3, category: '水产' },
      { name: '干煎阿根廷红虾', difficulty: 3, category: '水产' },
      { name: '红烧鲤鱼', difficulty: 3, category: '水产' },
      { name: '红烧鱼', difficulty: 3, category: '水产' },
      { name: '红烧鱼头', difficulty: 3, category: '水产' },
      { name: '黄油煎虾', difficulty: 2, category: '水产' },
      { name: '烤鱼', difficulty: 4, category: '水产' },
      { name: '酱炖蟹', difficulty: 4, category: '水产' },
      { name: '芥末黄油罗氏虾', difficulty: 3, category: '水产' },
      { name: '咖喱炒蟹', difficulty: 4, category: '水产' },
      { name: '鲤鱼炖白菜', difficulty: 3, category: '水产' },
      { name: '清蒸鲈鱼', difficulty: 2, category: '水产' },
      { name: '清蒸生蚝', difficulty: 2, category: '水产' },
      { name: '肉蟹煲', difficulty: 5, category: '水产' },
      { name: '水煮鱼', difficulty: 4, category: '水产' },
      { name: '蒜蓉虾', difficulty: 2, category: '水产' },
      { name: '蒜香黄油虾', difficulty: 2, category: '水产' },
      { name: '糖醋鲤鱼', difficulty: 4, category: '水产' },
      { name: '微波葱姜黑鳕鱼', difficulty: 2, category: '水产' },
      { name: '香煎翘嘴鱼', difficulty: 3, category: '水产' },
      { name: '响油鳝丝', difficulty: 4, category: '水产' },
      { name: '小龙虾', difficulty: 4, category: '水产' },
      { name: '油焖大虾', difficulty: 3, category: '水产' },
      { name: '茶叶蛋', difficulty: 2, category: '早餐' },
      { name: '蛋煎糍粑', difficulty: 3, category: '早餐' },
      { name: '桂圆红枣粥', difficulty: 2, category: '早餐' },
      { name: '韩国麻药鸡蛋', difficulty: 3, category: '早餐' },
      { name: '鸡蛋三明治', difficulty: 1, category: '早餐' },
      { name: '煎饺', difficulty: 2, category: '早餐' },
      { name: '金枪鱼酱三明治', difficulty: 1, category: '早餐' },
      { name: '空气炸锅面包片', difficulty: 1, category: '早餐' },
      { name: '美式炒蛋', difficulty: 2, category: '早餐' },
      { name: '牛奶燕麦', difficulty: 1, category: '早餐' },
      { name: '手抓饼', difficulty: 2, category: '早餐' },
      { name: '水煮玉米', difficulty: 1, category: '早餐' },
      { name: '苏格兰蛋', difficulty: 4, category: '早餐' },
      { name: '太阳蛋', difficulty: 2, category: '早餐' },
      { name: '溏心蛋', difficulty: 2, category: '早餐' },
      { name: '吐司果酱', difficulty: 1, category: '早餐' },
      { name: '完美水煮蛋', difficulty: 1, category: '早餐' },
      { name: '微波炉蛋糕', difficulty: 2, category: '早餐' },
      { name: '微波炉荷包蛋', difficulty: 1, category: '早餐' },
      { name: '微波炉蒸蛋', difficulty: 1, category: '早餐' },
      { name: '温泉蛋', difficulty: 2, category: '早餐' },
      { name: '燕麦鸡蛋饼', difficulty: 2, category: '早餐' },
      { name: '意式香肠北非蛋', difficulty: 3, category: '早餐' },
      { name: '蒸花卷', difficulty: 3, category: '早餐' },
      { name: '蒸水蛋', difficulty: 2, category: '早餐' },
      { name: '炒方便面', difficulty: 2, category: '主食' },
      { name: '炒河粉', difficulty: 3, category: '主食' },
      { name: '炒凉粉', difficulty: 3, category: '主食' },
      { name: '炒馍', difficulty: 2, category: '主食' },
      { name: '炒年糕', difficulty: 2, category: '主食' },
      { name: '炒意大利面', difficulty: 2, category: '主食' },
      { name: '葱油拌面', difficulty: 2, category: '主食' },
      { name: '蛋包饭', difficulty: 3, category: '主食' },
      { name: '蛋炒饭', difficulty: 1, category: '主食' },
      { name: '电饭煲三文鱼炊饭', difficulty: 2, category: '主食' },
      { name: '豆角焖面', difficulty: 3, category: '主食' },
      { name: '韩式拌饭', difficulty: 2, category: '主食' },
      { name: '河南蒸面条', difficulty: 3, category: '主食' },
      { name: '红芸豆拌饭', difficulty: 2, category: '主食' },
      { name: '火腿饭团', difficulty: 2, category: '主食' },
      { name: '基础牛奶面包', difficulty: 4, category: '主食' },
      { name: '茄子肉煎饼', difficulty: 3, category: '主食' },
      { name: '鲣鱼海苔玉米饭', difficulty: 1, category: '主食' },
      { name: '酱拌荞麦面', difficulty: 2, category: '主食' },
      { name: '韭菜盒子', difficulty: 4, category: '主食' },
      { name: '可乐炒饭', difficulty: 2, category: '主食' },
      { name: '空气炸锅照烧鸡饭', difficulty: 2, category: '主食' },
      { name: '醪糟小汤圆', difficulty: 2, category: '主食' },
      { name: '老干妈拌面', difficulty: 1, category: '主食' },
      { name: '老友猪肉粉', difficulty: 3, category: '主食' },
      { name: '烙饼', difficulty: 3, category: '主食' },
      { name: '利提巧卡', difficulty: 3, category: '主食' },
      { name: '凉粉', difficulty: 2, category: '主食' },
      { name: '螺蛳粉', difficulty: 3, category: '主食' },
      { name: '麻辣减脂荞麦面', difficulty: 2, category: '主食' },
      { name: '麻油拌面', difficulty: 1, category: '主食' },
      { name: '电饭煲蒸米饭', difficulty: 1, category: '主食' },
      { name: '煮锅蒸米饭', difficulty: 2, category: '主食' },
      { name: '披萨饼皮', difficulty: 4, category: '主食' },
      { name: '热干面', difficulty: 3, category: '主食' },
      { name: '日式肥牛丼饭', difficulty: 2, category: '主食' },
      { name: '日式咖喱饭', difficulty: 2, category: '主食' },
      { name: '肉蛋盖饭', difficulty: 2, category: '主食' },
      { name: '陕西油泼面', difficulty: 3, category: '主食' },
      { name: '芝麻烧饼', difficulty: 4, category: '主食' },
      { name: '手工水饺', difficulty: 3, category: '主食' },
      { name: '酸辣蕨根粉', difficulty: 2, category: '主食' },
      { name: '汤面', difficulty: 1, category: '主食' },
      { name: '微波炉腊肠煲仔饭', difficulty: 2, category: '主食' },
      { name: '西红柿鸡蛋挂面', difficulty: 1, category: '主食' },
      { name: '鲜肉烧卖', difficulty: 4, category: '主食' },
      { name: '咸肉菜饭', difficulty: 3, category: '主食' },
      { name: '扬州炒饭', difficulty: 3, category: '主食' },
      { name: '意式肉酱面', difficulty: 3, category: '主食' },
      { name: '印度烤饼', difficulty: 3, category: '主食' },
      { name: '印度焖饭', difficulty: 3, category: '主食' },
      { name: '鹰嘴豆炸饼', difficulty: 4, category: '主食' },
      { name: '炸酱面', difficulty: 3, category: '主食' },
      { name: '照烧鸡腿饭', difficulty: 2, category: '主食' },
      { name: '蒸卤面', difficulty: 3, category: '主食' },
      { name: '中式馅饼', difficulty: 4, category: '主食' },
      { name: '猪油拌饭', difficulty: 1, category: '主食' },
      { name: '煮泡面加蛋', difficulty: 1, category: '主食' },
      { name: '半成品意面', difficulty: 1, category: '半成品加工' },
      { name: '空气炸锅鸡翅中', difficulty: 2, category: '半成品加工' },
      { name: '空气炸锅羊排', difficulty: 2, category: '半成品加工' },
      { name: '懒人蛋挞', difficulty: 2, category: '半成品加工' },
      { name: '凉皮', difficulty: 3, category: '半成品加工' },
      { name: '牛油火锅底料', difficulty: 3, category: '半成品加工' },
      { name: '速冻馄饨', difficulty: 1, category: '半成品加工' },
      { name: '速冻水饺', difficulty: 1, category: '半成品加工' },
      { name: '速冻汤圆', difficulty: 1, category: '半成品加工' },
      { name: '炸薯条', difficulty: 2, category: '半成品加工' },
      { name: '昂刺鱼豆腐汤', difficulty: 3, category: '汤与粥' },
      { name: '陈皮排骨汤', difficulty: 3, category: '汤与粥' },
      { name: '番茄牛肉蛋花汤', difficulty: 3, category: '汤与粥' },
      { name: '勾芡香菇汤', difficulty: 2, category: '汤与粥' },
      { name: '黄瓜皮蛋汤', difficulty: 2, category: '汤与粥' },
      { name: '金针菇汤', difficulty: 1, category: '汤与粥' },
      { name: '菌菇炖乳鸽', difficulty: 5, category: '汤与粥' },
      { name: '腊八粥', difficulty: 3, category: '汤与粥' },
      { name: '罗宋汤', difficulty: 4, category: '汤与粥' },
      { name: '米粥', difficulty: 1, category: '汤与粥' },
      { name: '奶油蘑菇汤', difficulty: 3, category: '汤与粥' },
      { name: '排骨苦瓜汤', difficulty: 3, category: '汤与粥' },
      { name: '皮蛋瘦肉粥', difficulty: 2, category: '汤与粥' },
      { name: '生汆丸子汤', difficulty: 4, category: '汤与粥' },
      { name: '西红柿鸡蛋汤', difficulty: 1, category: '汤与粥' },
      { name: '小米粥', difficulty: 1, category: '汤与粥' },
      { name: '羊肉汤', difficulty: 4, category: '汤与粥' },
      { name: '银耳莲子粥', difficulty: 2, category: '汤与粥' },
      { name: '玉米排骨汤', difficulty: 3, category: '汤与粥' },
      { name: '朱雀汤', difficulty: 2, category: '汤与粥' },
      { name: '紫菜蛋花汤', difficulty: 1, category: '汤与粥' },
      { name: '耙耙柑茶', difficulty: 2, category: '饮料' },
      { name: '百香果橙子特调', difficulty: 2, category: '饮料' },
      { name: '冰粉', difficulty: 2, category: '饮料' },
      { name: '菠萝咖啡特调', difficulty: 2, category: '饮料' },
      { name: '冬瓜茶', difficulty: 2, category: '饮料' },
      { name: '海边落日', difficulty: 3, category: '饮料' },
      { name: '金菲士', difficulty: 3, category: '饮料' },
      { name: '金汤力', difficulty: 2, category: '饮料' },
      { name: '酒酿醪糟', difficulty: 2, category: '饮料' },
      { name: '可乐桶', difficulty: 2, category: '饮料' },
      { name: '奶茶', difficulty: 3, category: '饮料' },
      { name: '柠檬水', difficulty: 1, category: '饮料' },
      { name: '牛油果拉西', difficulty: 3, category: '饮料' },
      { name: '奇异果菠菜特调', difficulty: 2, category: '饮料' },
      { name: '砂糖椰子冰沙', difficulty: 2, category: '饮料' },
      { name: '酸梅汤', difficulty: 2, category: '饮料' },
      { name: '泰国手标红茶', difficulty: 2, category: '饮料' },
      { name: '杨枝甘露', difficulty: 4, category: '饮料' },
      { name: '印度奶茶', difficulty: 2, category: '饮料' },
      { name: '长岛冰茶', difficulty: 3, category: '饮料' },
      { name: 'B52轰炸机', difficulty: 2, category: '饮料' },
      { name: 'Mojito莫吉托', difficulty: 2, category: '饮料' },
      { name: '草莓酱', difficulty: 2, category: '酱料和其它材料' },
      { name: '葱油', difficulty: 2, category: '酱料和其它材料' },
      { name: '简易版炒糖色', difficulty: 2, category: '酱料和其它材料' },
      { name: '蒜香酱油', difficulty: 1, category: '酱料和其它材料' },
      { name: '糖醋汁', difficulty: 2, category: '酱料和其它材料' },
      { name: '油泼辣子', difficulty: 2, category: '酱料和其它材料' },
      { name: '油酥', difficulty: 2, category: '酱料和其它材料' },
      { name: '炸串酱料', difficulty: 3, category: '酱料和其它材料' },
      { name: '蔗糖糖浆', difficulty: 1, category: '酱料和其它材料' },
      { name: '奥利奥冰淇淋', difficulty: 3, category: '甜品' },
      { name: '草莓冰淇淋', difficulty: 4, category: '甜品' },
      { name: '反沙芋头', difficulty: 4, category: '甜品' },
      { name: '龟苓膏', difficulty: 2, category: '甜品' },
      { name: '红柚蛋糕', difficulty: 4, category: '甜品' },
      { name: '胡萝卜甜糕', difficulty: 3, category: '甜品' },
      { name: '咖啡椰奶冻', difficulty: 3, category: '甜品' },
      { name: '烤蛋挞', difficulty: 3, category: '甜品' },
      { name: '烤箱版巴斯克芝士蛋糕', difficulty: 4, category: '甜品' },
      { name: '玛格丽特饼干', difficulty: 3, category: '甜品' },
      { name: '魔芋蛋糕', difficulty: 3, category: '甜品' },
      { name: '戚风蛋糕', difficulty: 4, category: '甜品' },
      { name: '酸奶意式奶冻', difficulty: 3, category: '甜品' },
      { name: '提拉米苏', difficulty: 5, category: '甜品' },
      { name: '无厨师机蜂蜜面包', difficulty: 3, category: '甜品' },
      { name: '雪花酥', difficulty: 3, category: '甜品' },
      { name: '英式司康', difficulty: 3, category: '甜品' },
      { name: '芋泥雪媚娘', difficulty: 4, category: '甜品' },
      { name: '炸鲜奶', difficulty: 4, category: '甜品' }
    ]
  },

  parseContent(text) {
    const lines = text.split('\n')
    const result = []
    let currentItem = null

    lines.forEach(line => {
      if (line.startsWith('## ')) {
        if (currentItem) result.push(currentItem)
        currentItem = { type: 'h2', text: line.replace('## ', '') }
      } else if (line.startsWith('### ')) {
        if (currentItem) result.push(currentItem)
        currentItem = { type: 'h3', text: line.replace('### ', '') }
      } else if (line.startsWith('- ')) {
        if (currentItem && currentItem.type === 'ul') {
          currentItem.items.push(line.replace('- ', ''))
        } else {
          if (currentItem) result.push(currentItem)
          currentItem = { type: 'ul', items: [line.replace('- ', '')] }
        }
      } else if (line.trim() === '') {
        if (currentItem) result.push(currentItem)
        currentItem = null
      } else if (line.match(/^\d+\./)) {
        if (currentItem && currentItem.type === 'ol') {
          currentItem.items.push(line)
        } else {
          if (currentItem) result.push(currentItem)
          currentItem = { type: 'ol', items: [line] }
        }
      } else {
        if (currentItem) result.push(currentItem)
        currentItem = { type: 'p', text: line }
      }
    })
    if (currentItem) result.push(currentItem)
    return result
  }
})
